name: CI

on: [push]

jobs:
  linux_build_3_6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dist
        run: python3.6 setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python3.6 -m pip install twine
          python3.6 -m twine upload -u __token__ -p ${{ secrets.pypi_password }}

  macos_build_3_6:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dist
        run: python3.6 setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python3.6 -m pip install twine
          python3.6 -m twine upload -u __token__ -p ${{ secrets.pypi_password }}

  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dist
        run: python3.6 setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python3.6 -m pip install twine
          python3.6 -m twine upload -u __token__ -p ${{ secrets.pypi_password }}
