name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8"]
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python -m pip install twine
          python -m twine upload -u __token__ -p ${{ secrets.pypi_password }}
